package constant

const (
	CRLFLength  = 2
	CRLF2Length = 4
)

var (
	Space        = []byte(" ")
	Colon        = []byte(":")
	QuestionMark = byte('?')
	SlashMark    = byte('/')
	CR           = byte('\r')
	CRLF         = []byte("\r\n")
	CRLF2        = []byte("\r\n\r\n")
)

var (
	MethodGet    = []byte("GET")
	MethodPost   = []byte("POST")
	DefaultProto = []byte("HTTP/1.1")
	DefaultPort  = []byte("80")
)

var (
	FormUrlEncoded          = []byte("application/x-www-form-urlencoded")
	FormMultiPart           = []byte("multipart/form-data")
	DefaultTransferEncoding = []byte("Transfer-Encoding: chunked")
)

var (
	FCGIContentType       = []byte("Content-type: ")
	FCGIContentTypeLength = len(FCGIContentType)
)

var (
	ChunkedEnd       = []byte("0\r\n\r\n")
	ChunkedEndLength = len(ChunkedEnd)
)

var (
	FieldHost          = []byte("Host: ")
	FieldContentType   = []byte("Content-Type: ")
	FieldContentLength = []byte("Content-Length: ")
	// FieldContentEncoding = []byte("Content-Encoding: ")
	// FieldContentLanguage = []byte("Content-Language: ")
	// FieldAccept          = []byte("Accept: ")
	// FieldAcceptEncoding  = []byte("Accept-Encoding: ")
	// FieldAcceptLanguage  = []byte("Accept-Language: ")
	// FieldAcceptCharset   = []byte("Accept-Charset: ")
	// FieldConnection      = []byte("Connection: ")
	// FieldNameUserAgent       = []byte("User-Agent: ")
	// FieldNameUpgradeInsecureRequests = []byte("Upgrade-Insecure-Requests: ")
	// FieldNameAcceptRanges            = []byte("Accept-Ranges: ")
	// FieldNameAge                     = []byte("Age: ")
	// FieldNameAllow                   = []byte("Allow: ")
	// FieldNameAuthorization           = []byte("Authorization: ")
	// FieldNameCacheControl            = []byte("Cache-Control: ")
	// FieldNameContentLocation         = []byte("Content-Location: ")
	// FieldNameContentMD5              = []byte("Content-MD5: ")
	// FieldNameContentRange            = []byte("Content-Range: ")
	// FieldNameDate                    = []byte("Date: ")
	// FieldNameETag                    = []byte("ETag: ")
	// FieldNameExpect                  = []byte("Expect: ")
	// FieldNameExpires                 = []byte("Expires: ")
	// FieldNameFrom                    = []byte("From: ")
	// FieldNameIfMatch                 = []byte("If-Match: ")
	// FieldNameIfModifiedSince         = []byte("If-Modified-Since: ")
	// FieldNameIfNoneMatch             = []byte("If-None-Match: ")
	// FieldNameIfRange                 = []byte("If-Range: ")
	// FieldNameIfUnmodifiedSince       = []byte("If-Unmodified-Since: ")
	// FieldNameLastModified            = []byte("Last-Modified: ")
	// FieldNameLocation                = []byte("Location: ")
	// FieldNameMaxForwards             = []byte("Max-Forwards: ")
	// FieldNamePragma                  = []byte("Pragma: ")
	// FieldNameProxyAuthenticate       = []byte("Proxy-Authenticate: ")
	// FieldNameProxyAuthorization      = []byte("Proxy-Authorization: ")
	// FieldNameRange                   = []byte("Range: ")
	// FieldNameReferer                 = []byte("Referer: ")
	// FieldNameRetryAfter              = []byte("Retry-After: ")
	// FieldNameServer                  = []byte("Server: ")
	// FieldNameTE                      = []byte("TE: ")
	// FieldNameTrailer                 = []byte("Trailer: ")
	// FieldNameTransferEncoding        = []byte("Transfer-Encoding: ")
	// FieldNameUpgrade                 = []byte("Upgrade: ")
	// FieldNameVary                    = []byte("Vary: ")
	// FieldNameVia                     = []byte("Via: ")
	// FieldNameWarning                 = []byte("Warning: ")
	// FieldNameWWWAuthenticate         = []byte("WWW-Authenticate: ")
)

var (
	FieldContentTypeLength = len(FieldContentType)
)

var (
	HeaderTemplate200 = []byte(" 200 OK\r\n")
	HeaderTemplate400 = []byte(" 400 Bad Request\r\n")
	HeaderTemplate404 = []byte(" 404 Not Found\r\n")
	HeaderTemplate406 = []byte(" 406 Not Acceptable\r\n")
	HeaderTemplate415 = []byte(" 415 Unsupported Media Type\r\n")
	HeaderTemplate500 = []byte(" 500 Internal Server Error\r\n")
	// HeaderTemplate100 = []byte(" 100 Continue\r\n")
	// HeaderTemplate101 = []byte(" 101 Switching Protocol\r\n")
	// HeaderTemplate103 = []byte(" 103 Early Hints\r\n")
	// HeaderTemplate201 = []byte(" 201 Created\r\n")
	// HeaderTemplate202 = []byte(" 202 Accepted\r\n")
	// HeaderTemplate203 = []byte(" 203 Non-Authoritative Information\r\n")
	// HeaderTemplate204 = []byte(" 204 No Content\r\n")
	// HeaderTemplate205 = []byte(" 205 Reset Content\r\n")
	// HeaderTemplate206 = []byte(" 206 Partial Content\r\n")
	// HeaderTemplate300 = []byte(" 300 Multiple Choices\r\n")
	// HeaderTemplate301 = []byte(" 301 Moved Permanently\r\n")
	// HeaderTemplate302 = []byte(" 302 Found\r\n")
	// HeaderTemplate303 = []byte(" 303 See Other\r\n")
	// HeaderTemplate304 = []byte(" 304 Not Modified\r\n")
	// HeaderTemplate305 = []byte(" 305 Use Proxy\r\n")
	// HeaderTemplate307 = []byte(" 307 Temporary Redirect\r\n")
	// HeaderTemplate401 = []byte(" 401 Unauthorized\r\n")
	// HeaderTemplate402 = []byte(" 402 Payment Required\r\n")
	// HeaderTemplate403 = []byte(" 403 Forbidden\r\n")
	// HeaderTemplate405 = []byte(" 405 Method Not Allowed\r\n")
	// HeaderTemplate407 = []byte(" 407 Proxy Authentication Required\r\n")
	// HeaderTemplate408 = []byte(" 408 Request Timeout\r\n")
	// HeaderTemplate409 = []byte(" 409 Conflict\r\n")
	// HeaderTemplate410 = []byte(" 410 Gone\r\n")
	// HeaderTemplate411 = []byte(" 411 Length Required\r\n")
	// HeaderTemplate412 = []byte(" 412 Precondition Failed\r\n")
	// HeaderTemplate413 = []byte(" 413 Request Entity Too Large\r\n")
	// HeaderTemplate414 = []byte(" 414 Request-URI Too Long\r\n")
	// HeaderTemplate416 = []byte(" 416 Requested Range Not Satisfiable\r\n")
	// HeaderTemplate417 = []byte(" 417 Expectation Failed\r\n")
	// HeaderTemplate501 = []byte(" 501 Not Implemented\r\n")
	// HeaderTemplate502 = []byte(" 502 Bad Gateway\r\n")
	// HeaderTemplate503 = []byte(" 503 Service Unavailable\r\n")
	// HeaderTemplate504 = []byte(" 504 Gateway Timeout\r\n")
	// HeaderTemplate505 = []byte(" 505 HTTP Version Not Supported\r\n")
)
